import {useMemo,useState,type ReactNode} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {Copy,ArrowUpDown,ChevronLeft,ChevronRight,SearchX,TriangleAlert} from 'lucide-react';
import type {Client,Role} from '../../types';
import {roles,number,shortGid} from '../../lib/data';
import {useData} from '../../app/context';
export function GidLabel({gid,link,full=false}:{gid:string;link?:string;full?:boolean}){const {notice}=useData();return <span className="gid-group"><span className="gid" title={gid}>{link?<Link to={link}>{full?gid:shortGid(gid)}</Link>:full?gid:shortGid(gid)}</span><button className="copy" title="Копировать полный GID" aria-label={'Копировать GID '+gid} onClick={e=>{e.stopPropagation();void navigator.clipboard.writeText(gid).then(()=>notice('Полный GID скопирован'),()=>notice('Не удалось скопировать GID'))}}><Copy size={12}/></button></span>}
export function RoleBadge({role}:{role?:Role}){return role?<span className="role-badge" style={{color:roles[role].color,background:roles[role].color+'12'}}><i style={{background:roles[role].color}}/>{roles[role].label}</span>:<span className="muted">Анализ не выполнен</span>}
export function PriorityScore({value}:{value?:number|null}){return value==null?<span className="muted">Нет данных</span>:<span className="priority-score" title={'Приоритет: '+value.toFixed(4)}>{number(value*100)}<small>/100</small></span>}
export function MetricCard({label,value,detail}:{label:string;value:ReactNode;detail?:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong>{detail&&<small>{detail}</small>}</div>}
export function EmptyState({title='Ничего не найдено',children}:{title?:string;children?:ReactNode}){return <div className="empty"><SearchX size={28}/><h3>{title}</h3>{children}</div>}
export function ErrorState({message,retry}:{message:string;retry?:()=>void}){return <div className="warning" role="alert"><TriangleAlert size={18}/><div>{message}{retry&&<button onClick={retry}>Повторить</button>}</div></div>}
export function Warning({children}:{children:ReactNode}){return <div className="warning"><TriangleAlert size={17}/><div>{children}</div></div>}
export function useQuery(){const [params,setParams]=useSearchParams();const update=(values:Record<string,string|null>)=>{const p=new URLSearchParams(params);Object.entries(values).forEach(([k,v])=>v?p.set(k,v):p.delete(k));setParams(p)};return {params,update}}
export function FilterBar({extended=false}:{extended?:boolean}){const {data}=useData();const {params,update}=useQuery();return <div className="filters">
  {extended&&<input aria-label="Поиск GID в таблице" placeholder="Поиск по GID" value={params.get('q')??''} onChange={e=>update({q:e.target.value,page:null})}/>}
  <select aria-label="Роль" value={params.get('role')??''} onChange={e=>update({role:e.target.value,page:null})}><option value="">Все роли</option>{Object.entries(roles).map(([key,r])=><option key={key} value={key}>{r.label}</option>)}</select>
  <select aria-label="Кластер" value={params.get('cluster')??''} onChange={e=>update({cluster:e.target.value,page:null})}><option value="">Все кластеры</option>{data.clusters.map(c=><option key={c.cluster_id} value={c.cluster_id}>Кластер {c.cluster_id}</option>)}</select>
  <label className="check"><input type="checkbox" checked={params.has('seed')} onChange={e=>update({seed:e.target.checked?'1':null,page:null})}/>Только seed</label>
  {extended&&<><select aria-label="Глубина" value={params.get('depth')??''} onChange={e=>update({depth:e.target.value,page:null})}><option value="">Любая глубина</option>{[0,1,2,3,4].map(d=><option value={d} key={d}>Глубина {d}</option>)}</select><label className="check"><input type="checkbox" checked={params.has('boundary')} onChange={e=>update({boundary:e.target.checked?'1':null,page:null})}/>Граница выгрузки</label><input className="narrow" aria-label="Минимальный приоритет" type="number" min="0" max="1" step="0.05" placeholder="Приоритет от" value={params.get('min')??''} onChange={e=>update({min:e.target.value,page:null})}/><input className="narrow" aria-label="Максимальный приоритет" type="number" min="0" max="1" step="0.05" placeholder="до 1" value={params.get('max')??''} onChange={e=>update({max:e.target.value,page:null})}/></>}
  <button className="text-button" onClick={()=>update({q:null,role:null,cluster:null,depth:null,seed:null,boundary:null,min:null,max:null,page:null})}>Сбросить</button>
  </div>}
export interface Column<T>{key:string;label:string;render:(row:T)=>ReactNode;sort?:(row:T)=>string|number;right?:boolean}
export function DataTable<T>({rows,columns,rowKey,onRow,initialSort,pageSize=25,queryKey='page'}:{rows:T[];columns:Column<T>[];rowKey:(row:T)=>string;onRow?:(row:T)=>void;initialSort?:string;pageSize?:number;queryKey?:string}){
  const {params,update}=useQuery();const [sort,setSort]=useState({key:initialSort??'',desc:!!initialSort});
  const sorted=useMemo(()=>{const col=columns.find(c=>c.key===sort.key);if(!col?.sort)return rows;return rows.map((r,i)=>({r,i})).sort((a,b)=>{const av=col.sort!(a.r),bv=col.sort!(b.r);return (typeof av==='number'&&typeof bv==='number'?av-bv:String(av).localeCompare(String(bv)))*(sort.desc?-1:1)||a.i-b.i}).map(x=>x.r)},[rows,columns,sort]);
  const pages=Math.max(1,Math.ceil(rows.length/pageSize));const page=Math.min(pages,Math.max(1,Number(params.get(queryKey))||1));
  if(!rows.length)return <EmptyState><p>Измените или очистите фильтры.</p></EmptyState>;
  return <div className="table-shell"><div className="table-scroll"><table><thead><tr>{columns.map(c=><th key={c.key} className={c.right?'numeric':''}>{c.sort?<button onClick={()=>{setSort({key:c.key,desc:sort.key===c.key?!sort.desc:true});update({[queryKey]:null})}}>{c.label}<ArrowUpDown size={12}/></button>:c.label}</th>)}</tr></thead><tbody>{sorted.slice((page-1)*pageSize,page*pageSize).map(r=><tr key={rowKey(r)} onClick={()=>onRow?.(r)} className={onRow?'clickable':''} tabIndex={onRow?0:undefined} onKeyDown={e=>{if(e.key==='Enter')onRow?.(r)}}>{columns.map(c=><td key={c.key} className={c.right?'numeric':''}>{c.render(r)}</td>)}</tr>)}</tbody></table></div><footer className="pagination"><span>{number(rows.length)} строк · {page} из {pages}</span><div><button aria-label="Предыдущая страница" disabled={page===1} onClick={()=>update({[queryKey]:String(page-1)})}><ChevronLeft size={16}/></button><button aria-label="Следующая страница" disabled={page===pages} onClick={()=>update({[queryKey]:String(page+1)})}><ChevronRight size={16}/></button></div></footer></div>;
}
export const clientColumns:Column<Client>[]=[{key:'gid',label:'GID',render:n=><GidLabel gid={n.gid} link={'/clients/'+n.gid}/>,sort:n=>n.gid},{key:'role',label:'Роль',render:n=><RoleBadge role={n.role}/>},{key:'role_score',label:'Оценка роли',render:n=>number(n.role_score),sort:n=>n.role_score??-1,right:true},{key:'priority_score',label:'Приоритет',render:n=><PriorityScore value={n.priority_score}/>,sort:n=>n.priority_score??-1,right:true},{key:'cluster_id',label:'Кластер',render:n=>n.cluster_id!=null?<Link to={'/clusters/'+n.cluster_id}>{n.cluster_id}</Link>:'Нет данных',sort:n=>n.cluster_id??-1},{key:'depth',label:'Глубина',render:n=><span className={n.depth===4?'boundary-text':''}>{n.depth}{n.depth===4?' · граница':''}</span>,sort:n=>n.depth},{key:'is_seed',label:'Seed',render:n=>n.is_seed?'Да':'Нет'},{key:'in_deg',label:'Отправители',render:n=>number(n.in_deg),sort:n=>n.in_deg,right:true},{key:'out_deg',label:'Получатели',render:n=>number(n.out_deg),sort:n=>n.out_deg,right:true},{key:'in_sum',label:'Поступления, KZT',render:n=>number(n.in_sum),sort:n=>n.in_sum,right:true},{key:'out_sum',label:'Отправления, KZT',render:n=>number(n.out_sum),sort:n=>n.out_sum,right:true},{key:'graph',label:'Связи',render:n=><Link to={'/graph?gid='+n.gid}>На графе</Link>}];
