import {useEffect,useRef,useState} from 'react';
import {NavLink,Outlet,useNavigate,useLocation} from 'react-router-dom';
import {Network,LayoutDashboard,Users,ReceiptText,Layers,ChartNoAxesCombined,Database,Settings,Search,Download,ChevronDown,CalendarDays,X} from 'lucide-react';
import {useData} from '../../app/context';
import {api} from '../../services/api';
import {dateLabel,shortGid} from '../../lib/data';
import {RoleBadge} from '../shared';
const navigation=[['/overview','Обзор',LayoutDashboard],['/graph','Граф',Network],['/clients','Клиенты',Users],['/transactions','Переводы',ReceiptText],['/clusters','Кластеры',Layers],['/analytics','Аналитика',ChartNoAxesCombined],['/data','Данные',Database],['/settings','Настройки',Settings]] as const;
export function Shell(){const {data,notice}=useData();const navigate=useNavigate(),location=useLocation();const [query,setQuery]=useState('');const [search,setSearch]=useState(false);const [exports,setExports]=useState(false);const [busy,setBusy]=useState(false);const input=useRef<HTMLInputElement>(null);
  useEffect(()=>{const fn=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSearch(true);input.current?.focus()}if(e.key==='Escape'){setSearch(false);setExports(false)}};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)},[]);
  useEffect(()=>{setSearch(false);setExports(false)},[location.pathname,location.search]);
  const found=data.nodes.filter(n=>query&&n.gid.includes(query));return <div className="app-shell"><nav className="rail" aria-label="Основная навигация"><NavLink to="/graph" className="brand-mark" title="MoneyGraph"><Network size={28}/></NavLink>{navigation.map(([path,label,Icon])=><NavLink key={path} to={path} title={label} className={({isActive})=>'rail-item '+(isActive?'active':'')}><Icon size={21}/><span>{label}</span></NavLink>)}</nav><div className="app-body"><header className="topbar"><div className="brand"><strong>MoneyGraph</strong><span>{data.meta.name}</span></div><div className="global-search"><Search size={16}/><input ref={input} value={query} aria-label="Поиск по GID" placeholder="Поиск по GID" onFocus={()=>setSearch(true)} onChange={e=>{setQuery(e.target.value);setSearch(true)}}/><kbd>⌘ K</kbd>{search&&<div className="search-results"><header><strong>Найти узел</strong><button aria-label="Закрыть поиск" onClick={()=>setSearch(false)}><X size={14}/></button></header>{!query?<p>Введите полный GID или его часть</p>:found.length?found.slice(0,30).map(n=><button key={n.gid} onClick={()=>{navigate('/graph?gid='+n.gid);setQuery('')}}><span className="gid" title={n.gid}>{n.gid}</span><RoleBadge role={n.role}/></button>):<p>Такого GID нет в загруженном наборе</p>}{found.length>30&&<p>Найдено {found.length}. Уточните GID.</p>}</div>}</div><div className="period"><CalendarDays size={16}/><span>{dateLabel(data.meta.period[0])} — {dateLabel(data.meta.period[1])}</span></div><span className="source-badge"><i/>{data.meta.mode==='real'?'Реальные данные':'Демо: синтетические данные'}</span><div className="export-menu"><button className="button button-primary" disabled={busy} onClick={()=>setExports(!exports)}><Download size={15}/>{busy?'Подготовка…':'Экспорт'}<ChevronDown size={13}/></button>{exports&&<div className="dropdown">{data.exports.length?data.exports.map(name=><button key={name} onClick={async()=>{setBusy(true);try{await api.download(name);notice(name+': файл получен и передан браузеру для скачивания')}catch(e){notice(String(e))}finally{setBusy(false);setExports(false)}}}>{name}</button>):<p>Анализ не выполнен. Полные выгрузки недоступны.</p>}</div>}</div></header><main className="workspace"><Outlet/></main></div></div>}
