from pathlib import Path

import pandas as pd

from moneygraph.io import RawData


def check_data(raw: RawData) -> dict:
    nodes, edges, tx = raw.nodes, raw.edges, raw.tx

    depth_dist = nodes["depth"].value_counts().sort_index().to_dict()
    seed_count = int(nodes["is_seed"].sum())

    out_deg = edges.groupby("src").size()
    in_deg = edges.groupby("dst").size()
    node_out_deg = nodes["gid"].map(out_deg).fillna(0).astype(int)
    node_in_deg = nodes["gid"].map(in_deg).fillna(0).astype(int)

    seed_mask = nodes["is_seed"]
    seeds_without_outflow = int(((seed_mask) & (node_out_deg == 0)).sum())

    depth4_mask = nodes["depth"] == 4
    censored = int((depth4_mask & (node_out_deg == 0)).sum())

    in_sum = nodes["gid"].map(edges.groupby("dst")["sum_kzt"].sum()).fillna(0.0)
    out_sum = nodes["gid"].map(edges.groupby("src")["sum_kzt"].sum()).fillna(0.0)
    out_gt_in = int((out_sum > in_sum).sum())

    date_has_time = bool((pd.to_datetime(tx["date"]).dt.time != pd.Timestamp("00:00:00").time()).any())

    self_loops_edges = int((edges["src"] == edges["dst"]).sum())
    self_loops_tx = int((tx["src"] == tx["dst"]).sum())

    tx_agg = tx.groupby(["src", "dst"]).agg(n_tx=("sum_kzt", "size"), sum_kzt=("sum_kzt", "sum")).reset_index()
    edges_idx = edges.set_index(["src", "dst"])
    tx_idx = tx_agg.set_index(["src", "dst"])
    n_tx_recon_diff = int(edges["n_tx"].sum() - len(tx))
    sum_kzt_recon_diff = float(edges["sum_kzt"].sum() - tx["sum_kzt"].sum())

    import networkx as nx
    Gn = nx.Graph()
    Gn.add_nodes_from(nodes["gid"])
    Gn.add_edges_from(zip(edges["src"], edges["dst"]))
    wcc_full = nx.number_connected_components(Gn)

    Ge = nx.Graph()
    Ge.add_edges_from(zip(edges["src"], edges["dst"]))
    wcc_edge_only = nx.number_connected_components(Ge)

    report = {
        "n_nodes": len(nodes),
        "n_edges": len(edges),
        "n_tx": len(tx),
        "n_seeds": seed_count,
        "depth_distribution": {str(k): int(v) for k, v in depth_dist.items()},
        "seeds_without_outflow": seeds_without_outflow,
        "censored_depth4_no_outflow": censored,
        "nodes_out_gt_in": out_gt_in,
        "date_has_time_component": date_has_time,
        "self_loops_edges": self_loops_edges,
        "self_loops_tx": self_loops_tx,
        "reconciliation_n_tx_diff": n_tx_recon_diff,
        "reconciliation_sum_kzt_diff": round(sum_kzt_recon_diff, 4),
        "wcc_full_node_graph": wcc_full,
        "wcc_edge_only_graph": wcc_edge_only,
    }
    return report


def write_data_notes(report: dict, docs_dir: str | Path = "docs") -> str:
    docs_dir = Path(docs_dir)
    docs_dir.mkdir(parents=True, exist_ok=True)
    path = docs_dir / "DATA_NOTES.md"

    lines = [
        "# DATA_NOTES",
        "",
        "Generated by `moneygraph.quality.check_data` on each pipeline run. Numbers below are",
        "measured from the real data in `data/`, not asserted in advance.",
        "",
        f"- nodes: {report['n_nodes']}, edges: {report['n_edges']}, transactions: {report['n_tx']}, seeds: {report['n_seeds']}",
        f"- depth distribution: {report['depth_distribution']}",
        f"- seeds without any observed outflow: {report['seeds_without_outflow']}",
        f"- depth-4 nodes with no outflow (censored, traversal artifact — never call these terminal): {report['censored_depth4_no_outflow']}",
        f"- nodes where out_sum > in_sum (likely unobserved inflow, not an error): {report['nodes_out_gt_in']}",
        f"- transaction dates carry a time component: {report['date_has_time_component']} "
        "(if False, same-day ordering within a date is unknown — temporal features are still computed on day granularity)",
        f"- self-loops: {report['self_loops_edges']} in edges, {report['self_loops_tx']} in transactions (excluded from the graph)",
        f"- edges vs transactions reconciliation: sum(n_tx) - count(transactions) = {report['reconciliation_n_tx_diff']}; "
        f"sum(edges.sum_kzt) - sum(transactions.sum_kzt) = {report['reconciliation_sum_kzt_diff']}",
        f"- weakly connected components on full node graph: {report['wcc_full_node_graph']}",
        f"- weakly connected components on edge-only subgraph: {report['wcc_edge_only_graph']}",
        "",
        "Known data limitations (see AGENTS.md): transfers below 5000 KZT are excluded from this export "
        "(an export threshold, not an AML threshold); the data covers July only, so inflow on the last "
        "days of the month may not yet have moved on (right-edge censoring, guarded by late_inflow_share); "
        "inflow is always a lower bound and seed inflow is essentially unobserved.",
    ]
    begin = "<!-- moneygraph:quality:start -->"
    end = "<!-- moneygraph:quality:end -->"
    generated = begin + "\n" + "\n".join(lines[2:]) + "\n" + end
    previous = path.read_text(encoding="utf-8") if path.exists() else ""
    if begin in previous and end in previous.split(begin, 1)[1]:
        prefix, rest = previous.split(begin, 1)
        _, suffix = rest.split(end, 1)
        content = prefix + generated + suffix
    elif previous.startswith("# DATA_NOTES\n\nGenerated by `moneygraph.quality.check_data`") and "\nKnown data limitations " in previous:
        # Migrate the legacy report, retaining everything appended after it.
        report_end = previous.find("\n", previous.index("\nKnown data limitations ") + 1)
        suffix = previous[report_end:] if report_end >= 0 else "\n"
        content = "# DATA_NOTES\n\n" + generated + suffix
    else:
        # An unfamiliar document is authored content, not disposable output.
        prefix = previous.rstrip() + "\n\n" if previous else "# DATA_NOTES\n\n"
        content = prefix + generated + "\n"
    path.write_text(content, encoding="utf-8")
    return str(path)
