import {useMemo} from 'react';
import {Link,useParams,useNavigate,useLocation} from 'react-router-dom';
import {Download} from 'lucide-react';
import {useData} from '../app/context';
import {clientColumns,DataTable,FilterBar,useQuery,EmptyState,Warning,MetricCard} from '../components/shared';
import {filterNodes,exportCsv,number,neighborhood,money,boundaryWarning} from '../lib/data';
import {NodeInspector} from '../components/shared/NodeInspector';
import {ActivityChart} from '../components/shared/ActivityChart';
import {GraphCanvas} from '../components/graph/GraphCanvas';
import {TransactionTable} from './TransactionsPage';
import type {NodeFilter} from '../types';
export function ClientsPage(){const {data,settings,setSettings,notice}=useData();const {params}=useQuery();const location=useLocation();const rows=useMemo(()=>filterNodes(data.nodes,Object.fromEntries(params) as NodeFilter),[data,params]);const columns=clientColumns.filter(c=>settings.columns.includes(c.key)||c.key==='graph').map(c=>c.key==='gid'?{...c,render:(n:typeof rows[number])=><Link className="gid" title={n.gid} to={'/clients/'+n.gid} state={{returnTo:location.pathname+location.search}}>{n.gid}</Link>}:c);return <div className="page"><header className="page-heading"><div><h1>Клиенты</h1><p>{number(rows.length)} из {number(data.nodes.length)} узлов</p></div><button onClick={()=>{exportCsv(rows,clientColumns.filter(c=>c.key!=='graph').map(c=>c.key),'clients_filtered.csv');notice('Таблица подготовлена для скачивания')}}><Download size={16}/>Экспорт фильтра</button></header><section className="panel"><FilterBar extended/><details className="column-picker"><summary>Видимые колонки</summary><div>{clientColumns.filter(c=>c.key!=='graph').map(c=><label key={c.key}><input type="checkbox" checked={settings.columns.includes(c.key)} disabled={c.key==='gid'} onChange={e=>setSettings({...settings,columns:e.target.checked?[...settings.columns,c.key]:settings.columns.filter(k=>k!==c.key)})}/>{c.label}</label>)}</div></details><DataTable rows={rows} columns={columns} rowKey={n=>n.gid} initialSort="priority_score"/></section></div>}
export function ClientPage(){const {gid=''}=useParams();const {data}=useData();const {params,update}=useQuery();const location=useLocation();const navigate=useNavigate();const n=data.nodes.find(n=>n.gid===gid);const tab=params.get('tab')??'overview';const tx=useMemo(()=>data.transactions.filter(t=>t.src===gid||t.dst===gid),[data,gid]);const ids=useMemo(()=>neighborhood(gid,data.edges,1,'both'),[data,gid]);const edges=useMemo(()=>data.edges.filter(e=>ids.has(e.src)&&ids.has(e.dst)),[data,ids]);const nodes=useMemo(()=>data.nodes.filter(n=>ids.has(n.gid)),[data,ids]);if(!n)return <EmptyState title="GID отсутствует в наборе"><Link to="/clients">К списку клиентов</Link></EmptyState>;return <div className="page"><div className="breadcrumbs"><Link to={location.state?.returnTo??'/clients'}>Клиенты</Link><span>/</span><span className="gid">{gid}</span></div><header className="page-heading"><div><h1>Карточка клиента</h1><p className="gid">{gid}</p></div><Link className="button button-primary" to={'/graph?gid='+gid}>Открыть на графе</Link></header>{n.depth===4&&<Warning>{boundaryWarning}</Warning>}<div className="tabs page-tabs">{[['overview','Обзор'],['relations','Связи'],['transactions','Транзакции'],['method','Методика']].map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>update({tab:k,txpage:null})}>{l}</button>)}</div>
  {tab==='overview'&&<div className="detail-grid"><section className="panel"><NodeInspector node={n}/></section><div><div className="metrics"><MetricCard label="Поступления" value={money(n.in_sum)}/><MetricCard label="Отправления" value={money(n.out_sum)}/></div><section className="panel padded"><h2>Активность клиента по дням</h2><p className="scope">Наблюдаемые переводы · KZT</p><ActivityChart transactions={tx} gid={gid}/></section><section className="panel padded"><h2>Дополнительные признаки backend</h2><dl className="features">{[['В цикле',n.in_cycle==null?'Нет данных':n.in_cycle?'Да':'Нет'],['Во встречной паре',n.in_2cycle==null?'Нет данных':n.in_2cycle?'Да':'Нет'],['Доля поздних поступлений',number(n.late_inflow_share)],['Доля быстрого транзита',number(n.fast_through_share)],['Посредничество',number(n.betweenness)]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></section></div></div>}
  {tab==='relations'&&<><section className="panel local-graph"><GraphCanvas nodes={nodes} edges={edges} selected={gid} local onSelect={id=>navigate('/clients/'+id+'?tab=relations')}/></section>{[['Отправители',data.edges.filter(e=>e.dst===gid).map(e=>e.src)],['Получатели',data.edges.filter(e=>e.src===gid).map(e=>e.dst)]].map(([title,list])=><section className="panel padded" key={title as string}><h2>{title}</h2><DataTable rows={data.nodes.filter(n=>(list as string[]).includes(n.gid))} rowKey={n=>n.gid} columns={clientColumns.slice(0,4)}/></section>)}</>}
  {tab==='transactions'&&<section className="panel"><TransactionTable transactions={tx}/></section>}
  {tab==='method'&&<section className="panel padded"><h2>Правила, применённые к узлу</h2>{n.rule_trace?<pre className="method-trace">{JSON.stringify(JSON.parse(n.rule_trace),null,2)}</pre>:<p>Трассировка правил для этого узла недоступна.</p>}<h2>Методика расчёта</h2><pre className="method-text">{data.methodology.text??'Методика недоступна'}</pre></section>}
  </div>}
