import {useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {PanelLeftClose,PanelLeftOpen,PanelRightClose,PanelRightOpen,ChevronDown,ChevronUp,X,SlidersHorizontal} from 'lucide-react';
import {useData} from '../app/context';
import {filterNodes,neighborhood,ranked,number,roles,clusterColor,money,shortGid} from '../lib/data';
import {FilterBar,RoleBadge,PriorityScore,useQuery,EmptyState,GidLabel} from '../components/shared';
import {GraphCanvas} from '../components/graph/GraphCanvas';
import {NodeInspector} from '../components/shared/NodeInspector';
import {ActivityChart} from '../components/shared/ActivityChart';
import {TransactionTable} from './TransactionsPage';
import type {Edge,NodeFilter} from '../types';
export function GraphPage(){const {data,settings}=useData();const {params,update}=useQuery();const [left,setLeft]=useState(true),[right,setRight]=useState(true),[bottom,setBottom]=useState(true),[filters,setFilters]=useState(false);const [edge,setEdge]=useState<Edge>();const [tab,setTab]=useState('activity');
  const requested=params.get('gid');const gid=requested===null&&!params.has('clear')?ranked(data.nodes).find(n=>n.priority_score!=null)?.gid:requested??undefined;
  const node=data.nodes.find(n=>n.gid===gid);const view=params.get('view')??(gid?'1':'all');const direction=params.get('direction')??'both';const color=(params.get('color')??settings.color) as 'role'|'cluster';
  const filtered=useMemo(()=>filterNodes(data.nodes,Object.fromEntries(params) as NodeFilter),[data,params]);const hidden=!!node&&!filtered.some(n=>n.gid===node.gid);
  const visible=useMemo(()=>{if(view==='all'||!gid)return filtered;const ids=neighborhood(gid,data.edges,+view,direction);return filtered.filter(n=>ids.has(n.gid))},[filtered,gid,view,direction,data.edges]);
  const edges=useMemo(()=>{const ids=new Set(visible.map(n=>n.gid));return data.edges.filter(e=>ids.has(e.src)&&ids.has(e.dst))},[visible,data.edges]);
  const select=(id:string)=>{update({gid:id,clear:null});setEdge(undefined);setRight(true)};
  const transactions=useMemo(()=>data.transactions.filter(t=>!gid||t.src===gid||t.dst===gid),[data,gid]);
  useEffect(()=>{const dst=params.get('edgeDst');if(dst&&gid)setEdge(data.edges.find(e=>e.src===gid&&e.dst===dst))},[params,gid,data.edges]);
  return <div className={'graph-workspace '+(!left?'left-closed ':'')+(!right?'right-closed':'')}>
    {left&&<aside className="panel priority-panel"><header className="panel-heading"><div><h2>Приоритет проверки</h2><span>{number(filtered.length)} узлов · по приоритету</span></div><button aria-label="Свернуть приоритеты" onClick={()=>setLeft(false)}><PanelLeftClose size={17}/></button></header><FilterBar/><div className="priority-list">{filtered.length?filtered.map((n,i)=><button key={n.gid} className={'priority-row '+(gid===n.gid?'selected':'')} onClick={()=>select(n.gid)}><span className="rank">{i+1}</span><div><div className="priority-row-head"><span className="gid" title={n.gid}>{shortGid(n.gid)}</span><PriorityScore value={n.priority_score}/></div><RoleBadge role={n.role}/><p>{n.evidence??'Анализ не выполнен'}</p></div></button>):<EmptyState><button onClick={()=>update({role:null,cluster:null,seed:null})}>Очистить фильтры</button></EmptyState>}</div><footer className="priority-foot">Оценка направляет проверку, не устанавливает виновность.</footer></aside>}
    <div className="graph-main"><section className="panel network-panel"><div className="graph-toolbar"><div className="segmented"><button className={view==='all'?'active':''} onClick={()=>update({view:'all'})}>Вся сеть</button><button className={view==='1'?'active':''} disabled={!gid} onClick={()=>update({view:'1'})}>1 шаг</button><button className={view==='2'?'active':''} disabled={!gid} onClick={()=>update({view:'2'})}>2 шага</button></div><select aria-label="Цвет графа" value={color} onChange={e=>update({color:e.target.value})}><option value="role">Цвет по роли</option><option value="cluster">Цвет по кластеру</option></select><button aria-label="Фильтры графа" title="Фильтры графа" onClick={()=>setFilters(!filters)}><SlidersHorizontal size={16}/></button>{!left&&<button title="Показать приоритеты" aria-label="Показать приоритеты" onClick={()=>setLeft(true)}><PanelLeftOpen size={17}/></button>}<button title={right?'Свернуть инспектор':'Показать инспектор'} aria-label={right?'Свернуть инспектор':'Показать инспектор'} onClick={()=>setRight(!right)}>{right?<PanelRightClose size={17}/>:<PanelRightOpen size={17}/>}</button></div>
      {filters&&<div className="graph-filters"><FilterBar/><select aria-label="Направление окружения" value={direction} onChange={e=>update({direction:e.target.value})}><option value="both">Оба направления</option><option value="in">Входящие</option><option value="out">Исходящие</option></select></div>}
      <div className="graph-caption"><div><h2>{view==='all'?'Обзор сети':'Окружение узла'}</h2><span>Показано {number(visible.length)} из {number(data.nodes.length)} узлов · {number(edges.length)} связей</span></div>{gid&&<button className="text-button" onClick={()=>{update({gid:null,clear:'1',view:'all'});setEdge(undefined)}}><X size={13}/>Сбросить выделение</button>}</div>
      {requested&&!node?<EmptyState title="GID отсутствует в наборе"><p className="gid">{requested}</p></EmptyState>:hidden?<EmptyState title="Узел существует, но скрыт текущими фильтрами"><button onClick={()=>update({role:null,cluster:null,seed:null,q:null,depth:null,boundary:null,min:null,max:null})}>Раскрыть узел</button></EmptyState>:<GraphCanvas nodes={visible} edges={edges} selected={gid} onSelect={select} onEdge={e=>{setEdge(e);setRight(true)}} onExpand={id=>update({gid:id,view:'2'})} local={view!=='all'} color={color}/>}
      <div className="graph-legend">{color==='role'?Object.entries(roles).map(([k,r])=><span key={k}><i style={{background:r.color}}/>{r.label}</span>):[...new Set(visible.map(n=>n.cluster_id).filter((id):id is number=>id!=null))].map(id=><span key={id}><i style={{background:clusterColor(id)}}/>Кластер {id}</span>)}<span className="seed-legend">◉ seed</span></div>
    </section><section className={'panel bottom-panel '+(!bottom?'collapsed':'')}><header className="panel-heading"><div className="tabs"><button className={tab==='activity'?'active':''} onClick={()=>{setTab('activity');setBottom(true)}}>Активность по дням</button><button className={tab==='tx'?'active':''} onClick={()=>{setTab('tx');setBottom(true)}}>Транзакции</button></div><button aria-label={bottom?'Свернуть нижнюю панель':'Развернуть нижнюю панель'} onClick={()=>setBottom(!bottom)}>{bottom?<ChevronDown size={16}/>:<ChevronUp size={16}/>}</button></header>{bottom&&<><p className="scope">{gid?'Узел '+shortGid(gid):'Вся выборка'} · {number(transactions.length)} переводов · KZT</p>{tab==='activity'?<ActivityChart transactions={transactions} gid={gid}/>:<TransactionTable transactions={transactions} small/>}</>}</section></div>
    {right&&<aside className="panel inspector"><button className="drawer-close" aria-label="Закрыть инспектор" onClick={()=>setRight(false)}><X size={18}/></button>{edge?<div className="inspector-content"><div className="section-label">Выбранная связь</div><h2>Наблюдаемые переводы</h2><p>Плательщик</p><GidLabel gid={edge.src} full link={'/clients/'+edge.src}/><p>Получатель</p><GidLabel gid={edge.dst} full link={'/clients/'+edge.dst}/><h2>{money(edge.sum_kzt)}</h2><p>{number(edge.n_tx)} переводов</p><Link className="button button-primary" to={'/transactions?src='+edge.src+'&dst='+edge.dst}>Открыть транзакции</Link><button onClick={()=>setEdge(undefined)}>Вернуться к узлу</button></div>:<NodeInspector node={node}/>}</aside>}
  </div>;
}
