import {useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {X,Download} from 'lucide-react';
import type {Transaction} from '../types';
import {useData} from '../app/context';
import {DataTable,GidLabel,useQuery} from '../components/shared';
import {money,number,dateLabel,exportCsv} from '../lib/data';
export function TransactionTable({transactions,small=false}:{transactions:Transaction[];small?:boolean}){const [selected,setSelected]=useState<Transaction>();const rows=useMemo(()=>transactions.map((t,i)=>({...t,key:String(i)})),[transactions]);return <><DataTable rows={rows} rowKey={r=>r.key} onRow={setSelected} pageSize={small?5:25} initialSort="date" queryKey="txpage" columns={[{key:'date',label:'Дата',render:t=>dateLabel(t.date),sort:t=>t.date},{key:'src',label:'Отправитель',render:t=><GidLabel gid={t.src} link={'/clients/'+t.src}/>},{key:'dst',label:'Получатель',render:t=><GidLabel gid={t.dst} link={'/clients/'+t.dst}/>},{key:'sum',label:'Сумма, KZT',render:t=>number(t.sum_kzt),sort:t=>t.sum_kzt,right:true}]}/>{selected&&<div className="drawer-backdrop" onClick={()=>setSelected(undefined)}><aside className="detail-drawer" role="dialog" aria-modal="true" aria-label="Детали операции" onClick={e=>e.stopPropagation()}><button className="close" aria-label="Закрыть детали операции" onClick={()=>setSelected(undefined)}><X size={18}/></button><h2>Детали операции</h2><p>{dateLabel(selected.date)}</p><h2>{money(selected.sum_kzt)}</h2><p>Отправитель</p><GidLabel gid={selected.src} full link={'/clients/'+selected.src}/><p>Получатель</p><GidLabel gid={selected.dst} full link={'/clients/'+selected.dst}/><p className="muted">Банковский идентификатор операции не предоставлен.</p><div className="inspector-actions"><Link to={'/graph?gid='+selected.src+'&view=1&edgeDst='+selected.dst}>Показать связь на графе</Link><Link to={'/clients/'+selected.src}>Открыть отправителя</Link><Link to={'/clients/'+selected.dst}>Открыть получателя</Link></div></aside></div>}</>}
export function TransactionsPage(){const {data,notice}=useData();const {params,update}=useQuery();const rows=useMemo(()=>data.transactions.filter(t=>(!params.get('gid')||t.src===params.get('gid')||t.dst===params.get('gid'))&&(!params.get('src')||t.src.includes(params.get('src')!))&&(!params.get('dst')||t.dst.includes(params.get('dst')!))&&(!params.get('from')||t.date.slice(0,10)>=params.get('from')!)&&(!params.get('to')||t.date.slice(0,10)<=params.get('to')!)&&(!params.get('minsum')||t.sum_kzt>=Number(params.get('minsum')))&&(!params.get('maxsum')||t.sum_kzt<=Number(params.get('maxsum')))),[data,params]);return <div className="page"><header className="page-heading"><div><h1>Транзакции</h1><p>Отдельные наблюдаемые переводы</p></div><button onClick={()=>{exportCsv(rows,['date','src','dst','sum_kzt'],'transactions_filtered.csv');notice('Выборка подготовлена и передана браузеру для скачивания')}}><Download size={16}/>Экспорт выборки</button></header><section className="panel"><div className="filters">{[['gid','Участие GID'],['src','Отправитель GID'],['dst','Получатель GID']].map(([k,label])=><input key={k} placeholder={label} aria-label={label} value={params.get(k)??''} onChange={e=>update({[k]:e.target.value,txpage:null})}/>)}{[['from','Дата от'],['to','Дата до']].map(([k,label])=><label key={k}>{label}<input aria-label={label} type="date" min={data.meta.period[0].slice(0,10)} max={data.meta.period[1].slice(0,10)} value={params.get(k)??''} onChange={e=>update({[k]:e.target.value,txpage:null})}/></label>)}{[['minsum','Сумма от'],['maxsum','Сумма до']].map(([k,label])=><input key={k} type="number" min="0" placeholder={label} aria-label={label} value={params.get(k)??''} onChange={e=>update({[k]:e.target.value,txpage:null})}/>)}<button onClick={()=>update({gid:null,src:null,dst:null,from:null,to:null,minsum:null,maxsum:null,txpage:null})}>Очистить</button></div><div className="table-summary"><strong>{number(rows.length)} переводов</strong><strong>{money(rows.reduce((s,t)=>s+t.sum_kzt,0))}</strong></div><p className="scope">Оценки рассчитаны за весь набор; фильтр меняет отображаемые переводы.</p><TransactionTable transactions={rows}/></section></div>}
